name: Meditation App Check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build with Gradle
        id: build
        run: ./gradlew build -x test

      - name: Test with Gradle
        id: test
        if: ${{ steps.build.conclusion == 'success' }}
        run: ./gradlew test