name: Meditation App Check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build with Gradle
        id: build
        run: ./gradlew build -x test

      - name: Unit test with Gradle
        id: test
        if: ${{ steps.build.conclusion == 'success' }}
        run: ./gradlew test
  androidTest:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: checkout
        uses: actions/checkout@v3

      - name: Android test with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest